<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Item::create(['item_code' => 'FG00001', 'item_name' => 'Indogel SGP-F08', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00003', 'item_name' => 'Indogel SGP-F20', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00004', 'item_name' => 'Indogel SGP-F27', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00005', 'item_name' => 'Indogel SGP-F28', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00006', 'item_name' => 'Indogel SGP-P04', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00009', 'item_name' => 'Indogel SGP-R10', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00010', 'item_name' => 'Indogel SGP-R12', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00011', 'item_name' => 'Indogel SGP-R10 (T)', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00501', 'item_name' => 'Indogel SGP-005M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00502', 'item_name' => 'Indogel SGP-028G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00506', 'item_name' => 'Indogel SGP-1183G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00507', 'item_name' => 'Indogel SGP-1187G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00508', 'item_name' => 'Indogel SGP-1222G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00510', 'item_name' => 'Indogel SGP-1385G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00511', 'item_name' => 'Indogel SGP-1522G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00512', 'item_name' => 'Indogel SGP-168M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00513', 'item_name' => 'Indogel SGP-172M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00516', 'item_name' => 'Indogel SGP-2020M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00517', 'item_name' => 'Indogel SGP-202A', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00518', 'item_name' => 'Indogel SGP-2082G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00520', 'item_name' => 'Indogel SGP-217G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00522', 'item_name' => 'Seaweed Extraxt (Indogel SGP-2211G)', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00523', 'item_name' => 'Indogel SGP-2252F', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00524', 'item_name' => 'Indogel SGP-236G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00526', 'item_name' => 'Indogel SGP-3105G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00527', 'item_name' => 'Indogel SGP-3115M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00529', 'item_name' => 'Indogel SGP-3383M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00532', 'item_name' => 'Indogel SGP-500M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00533', 'item_name' => 'Indogel SGP-5115M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00534', 'item_name' => 'Indogel SGP-5335G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00535', 'item_name' => 'Indogel SGP-550G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00536', 'item_name' => 'Indogel SGP-5755G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00542', 'item_name' => 'Indogel SGP-F246K', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00544', 'item_name' => 'Indogel SGP-F410K', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00545', 'item_name' => 'Indogel SGP-F420K', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00548', 'item_name' => 'Indogel SGP-2133M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00549', 'item_name' => 'Indogel SGP-1811M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00552', 'item_name' => 'Indogel SGP-1385G (R)', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00553', 'item_name' => 'Indogel SGP-2045G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00554', 'item_name' => 'Indogel SGP-1385G (T)', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00555', 'item_name' => 'Indogel SGP-1211G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01002', 'item_name' => 'Indolacta SGP-045D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01004', 'item_name' => 'Indolacta SGP-3403D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01005', 'item_name' => 'Indolacta SGP-220D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01006', 'item_name' => 'Indolacta SGP-2500D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01007', 'item_name' => 'Indolacta SGP-051D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01502', 'item_name' => 'Indovisco SGP-F20i', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG02003', 'item_name' => 'Indovisco SGP-505S', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG02501', 'item_name' => 'Eurogel MBE-3020', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG02502', 'item_name' => 'Eurogel MBE-3063', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG03502', 'item_name' => 'S-100 Fi', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00568', 'item_name' => 'Indogel SGP-2211G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00569', 'item_name' => 'Indogel SGP-5161M', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00571', 'item_name' => 'Indogel SGP-5310G', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG04503', 'item_name' => 'Indovisco SGP-R10i', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01009', 'item_name' => 'Indolacta SGP-230D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01010', 'item_name' => 'Indolacta SGP-032D', 'category' => 'Finished Goods', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'FG00012', 'item_name' => 'Indogel SGP-F08 (Hold)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00556', 'item_name' => 'Indogel SGP-236G (Hold)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00564', 'item_name' => 'Indogel SGP-2211G (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00567', 'item_name' => 'Indogel SGP-1385G (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG02006', 'item_name' => 'Indovisco SGP-505S (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00570', 'item_name' => 'Indogel SGP-5161M (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00572', 'item_name' => 'Indogel SGP-5310G (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG01008', 'item_name' => 'Indolacta SGP-220D (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00561', 'item_name' => 'Indogel SGP-2020M (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00566', 'item_name' => 'Indogel SGP-2045 G (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00573', 'item_name' => 'Seaweed Extract Powder (Indogel SGP-2211G) HOLD  ', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FG00574', 'item_name' => 'Indogel SGP-1183G (HOLD)', 'category' => 'Finished Goods HOLD', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'FB01401', 'item_name' => 'Gurih Jelly Melon Flavor ', 'category' => 'Gurih Jelly', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FB01402', 'item_name' => 'Gurih Jelly Lychee Flavor ', 'category' => 'Gurih Jelly', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FB01403', 'item_name' => 'Gurih Jelly Strawberry Flavor ', 'category' => 'Gurih Jelly', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'FB01404', 'item_name' => 'Gurih Jelly Orange Flavor ', 'category' => 'Gurih Jelly', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'FG09002', 'item_name' => 'Tehnical Powder', 'category' => 'Side Product', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00002', 'item_name' => 'Primary Blend F08', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00005', 'item_name' => 'Primary Blend F08ST', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00007', 'item_name' => 'Primary Blend F20', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00009', 'item_name' => 'Primary Blend F20ST', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00010', 'item_name' => 'Primary Blend F20i', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00012', 'item_name' => 'Primary Blend F20iST', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00013', 'item_name' => 'Primary Blend F20S/F28', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00014', 'item_name' => 'Primary Blend F27', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PB00021', 'item_name' => 'Primary Bland RJB', 'category' => 'PRIMARY BLEND', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00002', 'item_name' => 'BATCH POWDER F08', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00006', 'item_name' => 'BATCH POWDER F20', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00007', 'item_name' => 'BATCH POWDER F20i', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00010', 'item_name' => 'BATCH POWDER F20S', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00011', 'item_name' => 'BATCH POWDER F27', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00013', 'item_name' => 'BATCH POWDER F30i', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00018', 'item_name' => 'Powder Ex Lab Pure', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00019', 'item_name' => 'Powder Ex Lab Blended', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BP00020', 'item_name' => 'Reject Powder', 'category' => 'BATCH POWDER', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'BA00012', 'item_name' => 'Konjac Gum FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00019', 'item_name' => 'Refined Carrageenan Iota (BLI 1130) ', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00020', 'item_name' => 'Refined Carrageenan Kappa (BLK 1120) ', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00023', 'item_name' => 'Refined Carrageenan Kappa (KA80S)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00030', 'item_name' => 'Refined Carrageenan Kappa (KA120)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00059', 'item_name' => 'Refined Carrageenan Iota (BL 3031)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00063', 'item_name' => 'Refined Carrageenan BLN 1008', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00002', 'item_name' => 'Calcium Sulfate FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00003', 'item_name' => 'Sodium Carboxymenthyl Cellulose FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00004', 'item_name' => 'Cassia Gum FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00005', 'item_name' => 'Citric Acid Anhydrous', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00008', 'item_name' => 'Dextrose Monohydrate FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00011', 'item_name' => 'Guar Gum FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00013', 'item_name' => 'Locust Bean Gum', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00014', 'item_name' => 'Maltodextrin FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00016', 'item_name' => 'Pottasium Carbonate FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00017', 'item_name' => 'Potassium Chloride (KCL) FG  ', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00018', 'item_name' => 'Potassium Citrate USP', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00024', 'item_name' => 'Sodium Citrate FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00025', 'item_name' => 'SRC Iota', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00026', 'item_name' => 'SRC Kappa (F 08) ', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00027', 'item_name' => 'Tara Gum FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00028', 'item_name' => 'Xanthan Gum FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00029', 'item_name' => 'Anticaking Agent FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00031', 'item_name' => 'Powdered Sugar (gula halus)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00032', 'item_name' => 'Calcium Lactate', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00033', 'item_name' => 'Lychee Flavour (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00034', 'item_name' => 'Melon Flavour (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00035', 'item_name' => 'Orange Flavour (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00036', 'item_name' => 'Strawberry Flavour (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00039', 'item_name' => 'Colorant Carmoisine', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00040', 'item_name' => 'Colorant Sunset Yellow', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00041', 'item_name' => 'Colorant Apple Green', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00042', 'item_name' => 'Extract Lychee (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00043', 'item_name' => 'Extract Melon (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00044', 'item_name' => 'Extract Orange (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00045', 'item_name' => 'Extract Strawberry (powder)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00049', 'item_name' => 'Sodium Carbonate FG (Soda Ash)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00051', 'item_name' => 'Semi Refined Carrageenan Kappa', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00055', 'item_name' => 'Garam Food Grade', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00056', 'item_name' => 'Sodium Aginate FG', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00058', 'item_name' => 'SRC Kappa (F20)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00060', 'item_name' => 'Dextrose Monohydrate (Retain)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00061', 'item_name' => ' Potassium Chloride (KCL) (Retain)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00062', 'item_name' => ' Sodium Citrate (Retain)', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'RW00001', 'item_name' => 'Euchema Cottonii (EC) Tarakan', 'category' => 'RAW MATERIALS SEAWEED', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'RW00002', 'item_name' => 'Euchema Spinosum (ES) ', 'category' => 'RAW MATERIALS SEAWEED', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'RW00007', 'item_name' => 'Euchema Cottonii (EC) Tual', 'category' => 'RAW MATERIALS SEAWEED', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'PU00001', 'item_name' => 'Potassium Hydroxide', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00002', 'item_name' => 'Caustic Soda', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00003', 'item_name' => 'Calcium Hypochlorite', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00005', 'item_name' => 'Calcium Chloride', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00006', 'item_name' => 'Calcium Hydroxide', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00007', 'item_name' => 'Potassium Chloride (KCL)', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00008', 'item_name' => 'Garam Technical Grade', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00010', 'item_name' => 'Kalgen 351', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PU00011', 'item_name' => 'Sunox 605', 'category' => 'Chemical Process Utility', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);

        Item::create(['item_code' => 'PM00001', 'item_name' => 'Carton Sheet Bottom (120 x 100 cm)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00003', 'item_name' => 'Crate Carton (120 x 100 x 115 cm)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00005', 'item_name' => 'Metallic Clamps', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'PM00006', 'item_name' => 'Plastic Pallet Export (120 x 100 x 12 cm)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00007', 'item_name' => 'Plastic Pallet Export (120 x 80 x 12 cm)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00008', 'item_name' => 'Paper Bag Printed Indogum Standard', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00009', 'item_name' => 'Paper Bag Blank-Brown with Woven', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00010', 'item_name' => 'Paper Tape Brown', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00011', 'item_name' => 'Plastic Strapping Band', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00012', 'item_name' => 'Stretch Wrap Film (20 micron,50 cm x 1500 M)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00013', 'item_name' => 'Thread White', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00025', 'item_name' => 'Sachet Frutty Acid @ 1.5 gram ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00026', 'item_name' => 'Sachet Frutty Acid @ 1.5 gram ( roll ) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00027', 'item_name' => 'Sachet Gurih Jelly Melon Flavor @ 15 gr (Pcs) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00028', 'item_name' => 'Sachet Gurih Jelly Melon Flavor @ 15 gr ( roll ) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00029', 'item_name' => 'Sachet Gurih Jelly Lychee Flavor @ 15 gr (Pcs) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00030', 'item_name' => 'Sachet Gurih Jelly Lychee Flavor @ 15 gr ( roll ) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00031', 'item_name' => 'Sachet Gurih Jelly Strawberry Flavor @ 15 gr (Pcs) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00032', 'item_name' => 'Sachet Gurih Jelly Strawberry Flavor @ 15 gr ( roll ) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00033', 'item_name' => 'Sachet Gurih Jelly Orange Flavor @ 15 gr (Pcs) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00034', 'item_name' => 'Sachet Gurih Jelly Orange Flavor @ 15 gr ( roll ) ', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'PM00035', 'item_name' => 'Karton Box Gurih Jelly 2 x 5 x ( 2 x 10 x @ 15 gr )', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00036', 'item_name' => 'Partisi Karton Box Gurih Jelly 2 x 5 x ( 2 x 10 x @ 15 gr )', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00037', 'item_name' => 'Isolasi bening  Gurih Jelly', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00041', 'item_name' => 'Inner box Gurih Jelly Melon Flavor 20 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00042', 'item_name' => 'Inner box Gurih Jelly Lychee Flavor 20 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00043', 'item_name' => 'Inner box Gurih Jelly Strawberry Flavor 20 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00044', 'item_name' => 'Inner box Gurih Jelly Orange Flavor 20 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00058', 'item_name' => 'Label stiker KB gurih jelly (Lychee-renceng)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00059', 'item_name' => 'Label stiker KB gurih jelly (Strawberry-renceng)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00060', 'item_name' => 'Label stiker KB gurih jelly (Melon-renceng)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00061', 'item_name' => 'Label stiker KB gurih jelly (Orange-renceng)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00062', 'item_name' => 'Label stiker KB gurih jelly (Plain-renceng)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00063', 'item_name' => 'Label stiker KB gurih jelly (Lychee-inner box)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00064', 'item_name' => 'Label stiker KB gurih jelly (Strawberry-inner box)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00065', 'item_name' => 'Label stiker KB gurih jelly (Melon-inner box)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00066', 'item_name' => 'Label stiker KB gurih jelly (Orange-inner box)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00067', 'item_name' => 'Label stiker KB gurih jelly (Plain-inner box)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00068', 'item_name' => 'Label box isi KB (15 x 12 Sachet)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00069', 'item_name' => 'Inner box Gurih Jelly Melon Flavor 12 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00070', 'item_name' => 'Inner box Gurih Jelly Lychee Flavor 12 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00071', 'item_name' => 'Inner box Gurih Jelly Strawberry Flavor 12 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00072', 'item_name' => 'Inner box Gurih Jelly Orange Flavor 12 x @ 15 gr', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00073', 'item_name' => 'Sachet Gurih Jelly Melon Flavor @ 15 gr (roll)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00074', 'item_name' => 'Sachet Gurih Jelly Lychee Flavor @ 15 gr (roll)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00075', 'item_name' => 'Sachet Gurih Jelly Strawberry Flavor @ 15 gr (roll)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00076', 'item_name' => 'Sachet Gurih Jelly Orange Flavor @ 15 gr (roll)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00077', 'item_name' => 'Label stiker KB gurih jelly (Lychee-renceng) - Design Lama', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00078', 'item_name' => 'Label stiker KB gurih jelly (Lychee-inner box) - Design Lama', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00079', 'item_name' => 'Label stiker KB gurih jelly (Orange-renceng) - Design Lama', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'PM00080', 'item_name' => 'Label stiker KB gurih jelly (Orange-inner box) - Design Lama', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);
        Item::create(['item_code' => 'MS00001', 'item_name' => 'Ethyl Alcohol', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Ltr', 'note' => '']);
        Item::create(['item_code' => 'MS00002', 'item_name' => 'Masking Tape 2 inch', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'MS00003', 'item_name' => 'PE Liner 130', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'MS00004', 'item_name' => 'PE Liner 98', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'MS00006', 'item_name' => 'Tali Plastik Rafia', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Roll', 'note' => '']);
        Item::create(['item_code' => 'MS00008', 'item_name' => 'Karung Plastik Seaweed (120 x 90 cm)', 'category' => 'PACKAGING', 'sub_category' => '', 'unit' => 'Pcs', 'note' => '']);

        Item::create(['item_code' => 'BA00064', 'item_name' => 'Curdlan FT-N80', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
        Item::create(['item_code' => 'BA00065', 'item_name' => 'Curdlan FT-N90', 'category' => 'Raw Materials', 'sub_category' => 'BLENDED', 'unit' => 'Kgs', 'note' => '']);
    }
}
